// File generated by the Firebase CLI.
// https://github.com/firebase/flutterfire_cli

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1QFBUURr4CaD8GlkzMk6s-jDfFNro0ac',
    appId: '1:459677001326:android:da17a9fc13ffc0e75de87f',
    messagingSenderId: '459677001326',
    projectId: 'scholarship-app-bfe64',
    storageBucket: 'scholarship-app-bfe64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1QFBUURr4CaD8GlkzMk6s-jDfFNro0ac',
    appId: '1:459677001326:ios:a1234567890abcdef',
    messagingSenderId: '459677001326',
    projectId: 'scholarship-app-bfe64',
    storageBucket: 'scholarship-app-bfe64.firebasestorage.app',
    iosBundleId: 'com.example.scholarshipApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1QFBUURr4CaD8GlkzMk6s-jDfFNro0ac',
    appId: '1:459677001326:ios:a1234567890abcdef',
    messagingSenderId: '459677001326',
    projectId: 'scholarship-app-bfe64',
    storageBucket: 'scholarship-app-bfe64.firebasestorage.app',
    iosBundleId: 'com.example.scholarshipApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1QFBUURr4CaD8GlkzMk6s-jDfFNro0ac',
    appId: '1:459677001326:web:webappid',
    messagingSenderId: '459677001326',
    projectId: 'scholarship-app-bfe64',
    storageBucket: 'scholarship-app-bfe64.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1QFBUURr4CaD8GlkzMk6s-jDfFNro0ac',
    appId: '1:459677001326:web:webappid',
    messagingSenderId: '459677001326',
    projectId: 'scholarship-app-bfe64',
    storageBucket: 'scholarship-app-bfe64.firebasestorage.app',
  );
}
